# TCL File Generated by Component Editor 13.1
# Tue Sep 06 08:57:19 MSD 2016
# DO NOT MODIFY


# 
# dcfifo_to_qsys "dcfifo_to_qsys" v1.0
# Pavel Poliansky 2016.09.06.08:57:19
# DCFIFO to Qsys bridge
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module dcfifo_to_qsys
# 
set_module_property DESCRIPTION "DCFIFO to Qsys bridge"
set_module_property NAME dcfifo_to_qsys
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Pavel Poliansky"
set_module_property DISPLAY_NAME dcfifo_to_qsys
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL dcfifo_to_qsys
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file dcfifo_to_qsys.v VERILOG PATH dcfifo_to_qsys.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter FIFO_SIZE INTEGER 256
set_parameter_property FIFO_SIZE DEFAULT_VALUE 256
set_parameter_property FIFO_SIZE DISPLAY_NAME FIFO_SIZE
set_parameter_property FIFO_SIZE TYPE INTEGER
set_parameter_property FIFO_SIZE UNITS None
set_parameter_property FIFO_SIZE HDL_PARAMETER true
add_parameter FIFO_USEDW_WIDTH INTEGER 8
set_parameter_property FIFO_USEDW_WIDTH DEFAULT_VALUE 8
set_parameter_property FIFO_USEDW_WIDTH DISPLAY_NAME FIFO_USEDW_WIDTH
set_parameter_property FIFO_USEDW_WIDTH TYPE INTEGER
set_parameter_property FIFO_USEDW_WIDTH UNITS None
set_parameter_property FIFO_USEDW_WIDTH HDL_PARAMETER true
add_parameter FIFO_WIDTH INTEGER 16
set_parameter_property FIFO_WIDTH DEFAULT_VALUE 16
set_parameter_property FIFO_WIDTH DISPLAY_NAME FIFO_WIDTH
set_parameter_property FIFO_WIDTH TYPE INTEGER
set_parameter_property FIFO_WIDTH UNITS None
set_parameter_property FIFO_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point s0
# 
add_interface s0 avalon end
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock clock_sink
set_interface_property s0 associatedReset reset_sink
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 readLatency 0
set_interface_property s0 readWaitTime 1
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0
set_interface_property s0 ENABLED true
set_interface_property s0 EXPORT_OF ""
set_interface_property s0 PORT_NAME_MAP ""
set_interface_property s0 CMSIS_SVD_VARIABLES ""
set_interface_property s0 SVD_ADDRESS_GROUP ""

add_interface_port s0 avs_s0_write write Input 1
add_interface_port s0 avs_s0_read read Input 1
add_interface_port s0 avs_s0_address address Input 2
add_interface_port s0 avs_s0_writedata writedata Input 32
add_interface_port s0 avs_s0_readdata readdata Output 32
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint "s0"
set_interface_property interrupt_sender associatedClock clock_sink
set_interface_property interrupt_sender associatedReset reset_sink
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender avs_s0_interrupt irq Output 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink avalon_clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink avalon_reset reset Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock ""
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end dcfifo_data export Input FIFO_WIDTH
add_interface_port conduit_end dcfifo_wrreq export Input 1
add_interface_port conduit_end dcfifo_wrusedw export Output FIFO_USEDW_WIDTH
add_interface_port conduit_end dcfifo_wrempty export Output 1
add_interface_port conduit_end dcfifo_wrfull export Output 1
add_interface_port conduit_end dcfifo_wrclk export Input 1

